# Use the following Image as the starting point
# We use the same one as COMP1531
image: comp1531/automarking:latest

# Define the various pipelines
stages:
  - checks
  - lint

# Instead of an install pipeline, we run a seperate script for setting up
before_script:
  - npm install

# Here we define a pipeline component called 'tests'
# It runs whenever a change to master or a merge request has occured
# Only change this if you know what you are doing
tests:
  stage: checks
  only:
    - master
    - merge_requests
  script:
    - SERVER_LOG=$(mktemp)
    - npm run start >& $SERVER_LOG &
    - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || (cat $SERVER_LOG && exit 1)
    - timeout -s SIGINT 180s npm run test || (cat $SERVER_LOG && exit 1)
    - kill -SIGINT %1
    - sleep 2
    - cat $SERVER_LOG

# You can add more pipelines or pipelines components that do things like: tsc or eslint

lint:
  stage: lint
  only:
    - master
    - merge_requests
  script:
    - npm run lint
